### ISSUE TITLE
this.$setData() 方法无效

### ISSUE THREAD

**Issue by hetianhe** [tvfe/wxpage#1]
按照文档引入dist代码：
```
var P = require('../lib/wxpage')
var Header = require('../comps/header')

P('index', {
	comps: [
		Header,
	],
	data: {
		userName: '张三'
	},
	onLaunch: function () {
		console.log('## On index page launch')	
		this.$setData({
			userName:  '李四'
		})
	}
})
```

**Comment by switer** [comment]
onLaunch阶段页面并未实例化，所以$setData是无效的。建议是在onLaunch里通过$put存在数据，在onLoad的声明周期里通过$take获取

**Comment by luobingbing0207** [comment]
demo链接无效，麻烦给个demo

**Comment by switer** [comment]
@luobingbing0207 谢谢，[demo地址](https://github.com/tvfe/wxpage-app)已更新:

https://github.com/tvfe/wxpage#使用

**Comment by luobingbing0207** [comment]
@switer demo上面封装的组件，怎么相互之间传值、传递响应事件呢

**Comment by luobingbing0207** [comment]
@switer 能加qq交流么？或者加群，我qq：354344527

**Comment by switer** [comment]
@luobingbing0207 
1. 父-子组件的**通信**可以使用$emitter，用事件通信。
2. 目前小程序的Element与组件实例没有直接的绑定关系，以至于无法知道事件的触发是否发生在子组件，所以子组件的**事件处理方法也是挂载在父组件的实例上**，用于事件响应。
3. **传值**是通过`template`的`data`属性进行数据绑定：[https://github.com/tvfe/wxpage-app/blob/master/pages/index.wxml#L3](https://github.com/tvfe/wxpage-app/blob/master/pages/index.wxml#L3)

**Comment by luobingbing0207** [comment]
@switer 可以在demo上面，写上简单的事件响应传递、数据传递等等实例么。。。萌新瑟瑟发抖

**Comment by switer** [comment]
@luobingbing0207 
* [Source: 数据传递](https://github.com/tvfe/wxpage-app/blob/master/pages/index.wxml#L3) 一般直接使用ES6的[解构赋值](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)会方便很多
* 定义在[Source: 组件的事件方法](https://github.com/tvfe/wxpage-app/blob/master/comps/header.js#L18)实际上在实例化的时候会被挂载在父组件的实例上，这是wxpage在实现时候的技巧
* [Source: 父组件](https://github.com/tvfe/wxpage-app/blob/master/pages/index.js#L28) 向 [Source: 子组件](https://github.com/tvfe/wxpage-app/blob/master/comps/header.js#L18) 派发消息

**Comment by luobingbing0207** [comment]
@switer 可以在demo上面，写上简单的事件响应传递、数据传递等等实例么。。。萌新瑟瑟发抖，真的，你就那样子说，等于没说。压根就不会写呀。。。麻烦大佬写几个实例操作，我好跟着做。。拜托了，大佬

**Comment by switer** [comment]
@luobingbing0207 点进去的代码就是示例代码，也不能更详细。

**Comment by luobingbing0207** [comment]
@switer 能加qq指导下不？。真的急。。
第一次学年中写法：354344527

**Comment by switer** [comment]
@luobingbing0207 [demo](https://github.com/tvfe/wxpage-app) 已加上了注释

**Comment by luobingbing0207** [comment]
@switer 谢啦，大佬。。我去试试。。。

**Comment by luobingbing0207** [comment]
@switer 大佬。。子组件给父组件回传参数、事件，要怎么搞？

**Comment by switer** [comment]
@luobingbing0207 
**方法1** 你可以直接调用父组件上的方法。
**方法2** 用vm.$emit('xxx', data) 给父组件反向抛事件

**Comment by luobingbing0207** [comment]
@switer 能也在demo上标注、弄下实例不？？麻烦大佬了。。。解决了燃眉之急

**Comment by switer** [comment]
@luobingbing0207 

https://github.com/tvfe/wxpage-app/commit/8aed18f3f25d6a3a3ea72816c52586a32f0bdef4

**Comment by luobingbing0207** [comment]
@switer 麻烦大佬啦。。。我去愉快的封装玩耍去了。。。谢谢照顾小萌新

**Comment by luobingbing0207** [comment]
this.$emitter.$on is not a function;at "pages/index" page lifeCycleMethod onLoad function
TypeError: this.$emitter.$on is not a function  @switer 报错需要管么

**Comment by luobingbing0207** [comment]
用的你的demo

**Comment by luobingbing0207** [comment]
@switer 好了。。去掉一个$符号就OK了。。

**Comment by miuchan** [comment]
@luobingbing0207 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
