### ISSUE TITLE
关于template 和 组件

### ISSUE THREAD

**Issue by Kay0806** [tvfe/wxpage#13]
请问你们对组件的描述怎么包含官方文档中所提到的 template 和 组件，这两者不是不同的概念吗

**Comment by switer** [comment]
wxpage的组件概念是个“伪组件”，只是把一种比较通用方便的“组件化”方案定义为组件，与后续小程序迭代的原生组件化方案是两回事

**Comment by Kay0806** [comment]
懂了 谢谢
