### ISSUE TITLE
demo 页面onAwake 不生效问题

### ISSUE THREAD

**Issue by GoToBoy** [tvfe/wxpage#17]
前后台切换时候
![1528165623027](https://user-images.githubusercontent.com/2384105/40951793-25aba5ae-68ab-11e8-9d10-73e9faa330d9.jpg)

**Comment by GoToBoy** [comment]
第二个问题是：page的onShow 写错了么？
![1528167764725](https://user-images.githubusercontent.com/2384105/40952937-14dc0200-68b0-11e8-82d3-f60cdfbec34a.jpg)

**Comment by switer** [comment]
onAwake没问题
![onawke2](https://user-images.githubusercontent.com/1167668/40975848-e08ec984-68fe-11e8-825f-82d978c6bc56.png)

**Comment by switer** [comment]
onShow 有什么问题？

**Comment by GoToBoy** [comment]
没有问题，编辑器问题吧，我是直接调用工具栏的前后台切换不生效，你发的图片那个地方正常生效
![1528211413739](https://user-images.githubusercontent.com/2384105/40984956-9db6b880-6915-11e8-857a-c2aad62087b2.jpg)
