### ISSUE TITLE
大大，组件中(┬＿┬) 有地方不太明白

### ISSUE THREAD

**Issue by clevok** [tvfe/wxpage#23]
最近在看大大的代码，想学习学习，用在自己的小程序，遇到了不明白的地方

    <custom-component binding="$" ref="customComp"/>

大大上面那个，我在代码 `component.js` 找到了  对`ref`的地方

    var refs = {}
    def.attached = fns.wrapFun(def.attached, function () {
		var id = ++cid
		this.$id = id
		refs[id] = this
		this._$ref = this.properties.ref || this.properties._ref
		this.triggerEvent('ing', {
			id: this.$id,
			type: 'attached'
		})
    })

似乎是给组件定义来一个 properties为`ref`，存为this。

###  但是不明白的地方是
这个 `binding=“$”` 是做什么，我搜了下那几个文件，没找到

**Comment by switer** [comment]
这是一个实现父-子组件关系的`奇技淫巧`。


`binding` => `binding` => 绑定类型名为`ing`的事件，回调时候调用`$` 方法，

子组件在需要通知父组件的时候 `triggerEvent('ing')`

**Comment by clevok** [comment]
啊哈，soga，原来是 `bind:ing` 没往这地方想到，谢谢大大
