### ISSUE TITLE
最新版的有个小BUG

### ISSUE THREAD

**Issue by bluefox1688** [tvfe/wxpage#3]
在组件里执行`vm.$data().xxxx`无法获取数据，直接报错。
我在wxpage.js优化了下代码就都正常了，具体看截图。
原本是`ctx[cid]`，调整之后的代码为`ctx.data[cid] || {}`
![image](https://user-images.githubusercontent.com/11862797/29905679-afe4eb16-8e42-11e7-8e58-3002bd744084.png)

**Comment by switer** [comment]
Thanks，是 dist/wxpage.js 文件没有更新。

**Comment by bluefox1688** [comment]
那麻烦更新下哈，我们在用`wxpage`来开发项目，非常感谢

**Comment by switer** [comment]
更新了，抱歉没知会到。用最新的 dist/wxpage 文件即可
