### ISSUE TITLE
希望能够将以前的template与JS引入以实现动态组件引入添加回来

### ISSUE THREAD

**Issue by GodofHope** [tvfe/wxpage#40]
在demo版本里，组件是通过在html中import和在js中require实现的，这样的组件虽然没有后续官方新增的自定义组件中很强的生命周期与配置选项（比如样式隔离，函数作用域的改变）但是却可以利用template的is动态特性动态根据自身逻辑按照用户需要动态引入template并进行渲染。现在改成官方的自定义组件后，组件只能在开发的时候写死，没法现场进行动态引入了，所以大大能不能恢复一下以前的component，以实现动态组件引入？

**Comment by GodofHope** [comment]
或者说，如果换成现在使用官方自定义组件的模式，我将如何hack去实现组建的动态引用？我看wepy和mpvue都不支持这个功能。
---
我的需求是这样的，比如我有ABCDEFG九个组件（或者说小部件,内带一些简单的js逻辑），会根据用户的行为来决定在界面中部的位置去按照特定顺序渲染一个或多个组件，比如BCG，DEAF，CCAGG等。这样应该怎么用wxpage实现呢？demo中的wxpage是可以实现的，但是在基础库版本过高的时候又会出现问题。
---
衷心希望大大能够给一个好的解决思路，或者能帮忙将旧版的方式添加回来。

**Comment by switer** [comment]
每一个模板组件对应的JS逻辑都是复用的？

**Comment by switer** [comment]
或者可以提供个代码片段

**Comment by switer** [comment]
z这个示例是否满足需求？

https://developers.weixin.qq.com/s/7vVhJyms7X5k

**Comment by GodofHope** [comment]
哇，谢谢大大，有了一些思路了，我自己再实战一下~
