### ISSUE TITLE
大大能否考虑添加typescript支持呢

### ISSUE THREAD

**Issue by GodofHope** [tvfe/wxpage#46]
因为自己的vue项目也在使用typescript，觉得这种语言写起来比较舒服，bug也会很少。所以大大能否考虑添加ts支持？

**Comment by switer** [comment]
`wxpage`初衷为作为小程序的框架扩展，尽可能贴近原生，也就没有依赖额外的构建，如果小程序的官方开发者工具支持TS构建后，`wxpage`会快速跟上
