### ISSUE TITLE
最新版基础库2.6.5 onNavigate不起作用

### ISSUE THREAD

**Issue by GodofHope** [tvfe/wxpage#47]
[代码片段]( https://developers.weixin.qq.com/s/Cnr4Iwmh7d7R)

请问一下我这个问题出在哪？

补充：似乎我往下切基础库版本也不行了.....？我记得以前是好使的？大概有几个月没碰小程序了。。。。

再补充：心态崩了，在我的项目上，是模拟器好使，而真机不行。新建这个代码片段是哪个都不好使......
我传指针这个操作应该没问题啊?

再再补充：
我记得小程序进入界面在onLoad之前不是会执行一次深拷贝么？
所以问题是不是出现在......onNagivate的同时页面就已经执行页面对象的深拷贝了？我记得老版本的小程序对this的赋值是有效的啊？

**Comment by GodofHope** [comment]
请问一下我这个问题出在哪？

**Comment by GodofHope** [comment]
似乎我往下切版本也不行了.....？我记得以前是好使的？大概有几个月没碰小程序了

**Comment by switer** [comment]
我看下

**Comment by GodofHope** [comment]
大大有空的时候也解答一下其他几个问题呗......

**Comment by switer** [comment]
试了下你的代码片段，模拟器下可以正常进入onNavigate

**Comment by switer** [comment]
![1](https://user-images.githubusercontent.com/1167668/56090682-d372b380-5ed7-11e9-8475-476882e644fb.png)
