### ISSUE TITLE
请问extendPageBefore和extendPageAfter的区别以及注意事项？

### ISSUE THREAD

**Issue by GodofHope** [tvfe/wxpage#48]
目前框架应该是在小程序载入，先执行APP的onLuanch和onShow，首屏onload之前就会执行主包的扩展，之后执行所有主包的onPageLaunch，之后是首屏的onload？在触发分包界面的时侯先执行分包的扩展，之后执行所有分包页的onPageLaunch，然后是分包对应界面的周期函数？

请问我上面说的对么？

所以这两个方法的具体执行时间是什么时候呢？我感觉不到这两个方法有什么区别啊

补充：灵机一动，是一个不会覆盖同名函数，一个会覆盖同名函数么？求大大现身说法。

**Comment by switer** [comment]
`extendPageBefore`/`onPageLaunch`/`extendPageAfter` 都是处于页面实例构建过程，
`extendPageBefore` 在开始之时。
`onPageLaunch`在与`extendPageAfter`都是在构建结束之后，差异在于前者是页面级别的方法，后者是APP级别。
`onPageLaunch`在`extendPageAfter`之前的原因在于：page的层级在app之下，父对应生命周期理应在子(页面)之后，onPageLaunch执行完毕才能可以说是extendPage-After
