### ISSUE TITLE
onAppShow只执行一次

### ISSUE THREAD

**Issue by GoToBoy** [tvfe/wxpage#51]
onAppShow 只在初始化页面时候调用一次，

![image](https://user-images.githubusercontent.com/2384105/61041178-803fcc80-a404-11e9-93f9-badcd00a7c76.png)
看注释以及debug都不执行...
更改了调用了吗还是这边代码结构问题= =？

**Comment by GodofHope** [comment]
为什么不用onAwake

**Comment by GoToBoy** [comment]
> onAwake

了解～我用onAwake吧

**Comment by GoToBoy** [comment]
> 为什么不用onAwake

是不是应该更新下文档～

**Comment by GoToBoy** [comment]
这种方法对onShow、onHide 有效，对onAwake,onAppShow无效，因为我的组件要触发onAppShow
<img width="624" alt="image" src="https://user-images.githubusercontent.com/2384105/61107325-41685000-a4b2-11e9-825d-4410f16fa226.png">

**Comment by switer** [comment]
onAppShow 与 onShow不一样，属于扩展方式，如果要多次触发的话，应该用原生的onShow。
> 文档确实有疏漏，感谢反馈
