### ISSUE TITLE
QQ小程序截至0.1.27版本仍需要补全页面json

### ISSUE THREAD

**Issue by GodofHope** [tvfe/wxpage#54]
QQ小程序截至0.1.27版本仍需要补全页面json才可以使得分包路径可以正常跳转

**Comment by GodofHope** [comment]
我已经看wxpage的源码好几天了........大体上wxpage的工作方式都看懂了，但是我还是不知道这两个问题是如何产生的。

只要不使用wxpage正常跳转，模拟器可以直接跳转到分包页面，分包页面也可以正常显示自定义组件......

所以大概是wxpage的问题？(我看代码没发现什么问题.......)

知道大大比较忙，而且这个框架也不是很火，但是还是希望大大能够救救我.....

自己开发的小程序已经跟wxpage深度耦合了......小程序是纯公益的一个帮助我们学校新生的小程序....微信叫"myNenu"，QQ叫"in东师"。我还想用这个小程序继续帮助新生呢.....TAT

**Comment by switer** [comment]
不好意思，刚看到，我先看下问题

**Comment by GodofHope** [comment]
没关系没关系，只要大大肯帮忙就心满意足啦hhh

**Comment by switer** [comment]
微信下分包没问题，试了下QQ模拟器下not work，preloadRule 也不生效，问题我先反馈给QQ小程序的开发

**Comment by switer** [comment]
让小程序的开发确认了，缺失.json文件导致了分包失败，你先把test.json补上，后续他们会兼容的

**Comment by GodofHope** [comment]
哦哦哦，好的，所以无法加载自定义组件也是在这个问题嘛?

**Comment by switer** [comment]
补上页面的json文件后是否修复？

**Comment by GodofHope** [comment]
修复了，忘了回了不好意思，想请问一下fns里面的一些函数最后被挂载到哪里去了呢？
