### ISSUE TITLE
session的疑问

### ISSUE THREAD

**Issue by Mister-Hope** [tvfe/wxpage#56]
我看代码session的实现是这样的：有效时间写入负的启动时间戳，然后key的键值前面加上启动时间戳

库里的session很明显写入了本地存储，我没看到有任何一个逻辑是把它删除的呀？

和readme中的`小程序退出后session会消失`不符呀？

**Comment by GodofHope** [comment]
另外我正在编写typescript的类型声明文件。

**Comment by GodofHope** [comment]
另外readme少了一个bindReLaunch方法，麻烦大大确认下，无误的话我稍后提一个PR吧

**Comment by switer** [comment]
没问题
