### ISSUE TITLE
希望大神有时间修改下，跳转有时失效的问题

### ISSUE THREAD

**Issue by Anan2014** [tvfe/wxpage#61]
![微信图片_20191221162452](https://user-images.githubusercontent.com/12581519/71305409-7340f380-240e-11ea-84a9-87347e88332d.png)
1、page:ready方法只执行一次，
2、当页面销毁时 timer 定时器失效了

**Comment by switer** [comment]
提个PR呢？

**Comment by switer** [comment]
2秒确实有点长

**Comment by switer** [comment]
fix: 改为默认1秒，添加配置选项，见 => https://github.com/tvfe/wxpage/commit/516175f42ed2e0de748ebecdead6174bfe2b45e5
