### ISSUE TITLE
有其它方法页面获取APP里的信息，除了用getAPP()

### ISSUE THREAD

**Issue by Anan2014** [tvfe/wxpage#7]

**Comment by switer** [comment]
你具体想要获取的是哪些信息呢？

**Comment by Anan2014** [comment]
比如：获取全局设置 globalData

**Comment by switer** [comment]
通过 **WXPage** 挂在方法的方式：
```js
var A = require('./path/to/wxpage')
A({
  extendPageBefore: function (name, page) {
    page.$global = function (key, value) {
      var len = arguments.length
      if (len > 1) {
        getApp().globalData[key] = value
      } else if (len == 1) {
        return getApp().globalData[key]
      } else {
        return getApp().globalData
      }
    }
  }
})
```

在页面js里使用：
```js
this.$global()  // 获取全部
this.$global('my-data') // 获取某个值
this.$global('my-data', 'inner data') // 设值
```

**Comment by Anan2014** [comment]
试了下可以了，谢谢

**Comment by GodofHope** [comment]
这个我也想问一下为什么一定要调用一个函数呢？多余的函数调用与判断不是会带来额外的开销么？我下面这样做有什么缺点呢？

var A = require('./path/to/wxpage')
A({
  extendPageBefore: function (name, page) {
    page.$global = getApp().globalData;
  }
})
在页面js里使用：

this.$global  // 获取全部
this.$global['my-data'] // 获取某个值
this.$global['my-data'] = 'inner data' // 设值

**Comment by switer** [comment]
直接暴露全局源数据，不便于实现全局数据的读写控制，例如：

1. 针对某项进行写校验
2. 域的限制, 只允许在某页面读写
3. 读取可变值 this.$global('currentPage')
